spring:
  http:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  jpa:
    show-sql: true
    properties: 
      hibernate: 
        dialect: br.com.application.dialects.CustomMySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/Dames?useSSL=false
    username: workbench
    password: workbench
  environment: Test

