spring:
  http:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  jpa:
    show-sql: true
    properties: 
      hibernate: 
        dialect: br.com.application.dialects.CustomMySQLDialect
  jackson:
    date-format: yyyy-MM-dd HH:mm
server:
    compression:
        enabled: true
        mime-typess: text/html,text/css,application/javascript,application/json,application/font-sfnt,application/font-woff,application/font-woff2    

authentication:
  jwtToken:
    secret: secretkey
    expiration: 86400000